= User Authentication
:icons: font
:imagesdir: ./img/
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Abstract

This document describes how users (i.e., operators of the Vault deployment) may
authenticate to perform administrative tasks. It also describes the steps
necessary to generate root tokens.

== Pre-Requisites

* The `vault` binary.
* The `vault-init.kms` file containing the encrypted Vault unseal keys generated
  during the setup process.

== Introduction

Even though Vault supports authenticating Google Cloud IAM service accounts it
does not yet support authenticating normal users using their organization
credentials. As such, the easiest way for an operator to authenticate with Vault
is to use a _root token_.

[IMPORTANT]
====
Root tokens are extremely sensible pieces of information. They should be
generated whenever necessary but revoked as soon as the operation that requires
the token is completed. They should be kept in-memory and never displayed or
written to filesystem.
====

== Generating a Root Token

As a first step one must make sure that Vault is unsealed:

[source,bash]
----
$ export VAULT_ADDR="https://vault.example.com"
$ vault unseal
Vault is already unsealed.
----

Then, one needs to generate a _one-time password_ to use during the process:

[source,bash]
----
$ vault generate-root -genotp
OTP: <otp>
----
<1> The one-time password generated by Vault.

One will now need a quorum
footnote:[This usually means 3 keys (as the default number of unseal keys is 5).]
of unseal keys to generate an _encoded root token_:

[source,bash]
----
$ vault generate-root -otp="<otp>" "$(
    gcloud kms decrypt \
        --plaintext-file - \
        --ciphertext-file vault-init.kms \
        --keyring vault \
        --key init \
        --location global \
        | awk "NR==1" \
        | awk -F ": " '{print $2}'
)"
Nonce: 3bc26078-ae67-7597-1d04-8f312c8908e9
Started: true
Generate Root Progress: 1
Required Keys: 3
Complete: false

$ vault generate-root -otp="<otp>" -nonce="<nonce>" "$(
    gcloud kms decrypt \
        --plaintext-file - \
        --ciphertext-file vault-init.kms \
        --keyring vault \
        --key init \
        --location global \
        | awk "NR==2" \
        | awk -F ": " '{print $2}'
)"
Nonce: 3bc26078-ae67-7597-1d04-8f312c8908e9
Started: true
Generate Root Progress: 2
Required Keys: 3
Complete: false

$ vault generate-root -otp="<otp>" -nonce="<nonce>" "$(
    gcloud kms decrypt \
        --plaintext-file - \
        --ciphertext-file vault-init.kms \
        --keyring vault \
        --key init \
        --location global \
        | awk "NR==3" \
        | awk -F ": " '{print $2}'
)"
Nonce: 3bc26078-ae67-7597-1d04-8f312c8908e9
Started: true
Generate Root Progress: 3
Required Keys: 3
Complete: true

Encoded root token: <encoded-root-token>
----

As a final step one needs to decode the value obtained in the previous step:

[source,bash]
----
$ vault generate-root -otp="<otp>" -decode="<encoded-root-token>"
Root token: <root-token>
----
<1> One must replace `<otp>` with the value of the one-time password generated
    above.
<2> One must replace `<encoded-root-token>` with the value of the encoded root
    token obtained in the previous step.
<3> `<root-token>` contains the resulting root token.

At this point, `<root-token>` can be used to authenticate as root.

== Authenticating as Root

To authenticate as root one must run

[source,bash]
----
$ vault auth
Token (will be hidden): <1>
Successfully authenticated! You are now logged in.
token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
token_duration: 0
token_policies: [root]
----
<1> One should input the value of  `<root-token>` obtained in the previous step.


== Revoking a Root Token

To revoke the root token when operations on Vault are completed one must run

[source,bash]
----
$ vault token-revoke -self
Success! Token revoked if it existed.

$ vault token-lookup
error looking up token: Error making API request.

URL: GET https://vault.example.com/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
----

== Further Reading

* https://www.vaultproject.io/docs/auth/token.html[Auth Backend: Token]
* https://www.vaultproject.io/docs/concepts/tokens.html[Tokens]
