= Secret Provisioning
:icons: font
:imagesdir: ./img/
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Abstract

This document describes the steps necessary to provision secrets in Vault.
Secrets are sensitive pieces of information that should be stored and managed
safely such as passwords and API keys (among others).

== Pre-Requisites

* The Vault binary.
* Being authenticated as `root` in Vault.

== Understanding a Vault Secret

A Vault secret is a set of key-value pairs stored on a given path (usually
`secret/<secret-name>`. For example:

[source,bash]
----
$ vault read secret/foo # <1>
Key             	Value
---             	-----
refresh_interval	768h0m0s
bar             	1
baz             	2
----
<1> Ask Vault to display the secret named `foo`.

This allow one to see that the `foo` secret has two keys — `foo` and `bar`.
Vault's output also shows each key's value — the secrets themselves. The fact
that Vault's secrets are in fact a set of key-value pairs makes it easy to group
related secrets under one path:

[source,bash]
----
$ vault read secret/aws-s3 # <1>
Key             	Value
---             	-----
refresh_interval	768h0m0s
access          	AKIAJLEH9DASPRQDZ4DK
secret          	guJClFKvBi6JV9METqcpgL8d73Xq48X4la91DBML
----
<1> Ask Vault to display the secret named `aws-s3`.

== Creating a Vault Secret

To create a Vault secret one must run

[source,bash]
----
$ vault write \
>     secret/<secret-name> # <1>
>     <key>=<value> # <2><3>
----
<1> One must replace `<secret-name>` with the name of the secret to be created.
<2> One must replace `<key>` with the name of the key inside the secret.
<3> One must replace `<value>` with the value of the secret to store in `<key>`.

[IMPORTANT]
====
One should mind that commands that are run are stored in the shell's history. If
one's shell has the ability to prevent a command from being written to history
it should be used *_whenever a secret is created_*.
====

[TIP]
====
This command can be used to add new keys to a secret whenever necessary.
====

== Further Reading

* https://www.vaultproject.io/docs/secrets/kv/index.html[Key/Value Secret Backend]
* https://www.vaultproject.io/api/secret/kv/index.html[Key/Value Secret Backend HTTP API]
